# Copyright 2022 leorize <leorize+oss@disroot.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Setup Nimskull environment
description: Setup a Nimskull environment then add it to PATH
inputs:
  token:
    description: The Github token to retrieve data from nimskull repository
    default: ${{ github.token }}
  nimskull-version:
    description: The semver specification for nimskull version to use. Defaults to any version
    default: '*'
  check-latest:
    description: Whether to always check for the latest version satisfying the given spec. Defaults to true as nimskull is still in pre-alpha status.
    default: true
outputs:
  path:
    description: The resulting installation location
  binPath:
    description: Where binaries were installed
  version:
    description: The installed version
  commit:
    description: The commit of the compiler

runs:
  using: 'node16'
  main: 'dist/index.js'
